name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      test-path:
        description: "Path to the test folder for this project"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || true
          pip install pytest

      - name: Run pytest
        run: pytest ${{ inputs.test-path }}
